### ISSUE TITLE
spla 1.6.0 doesn't compile with rocblas 6.0.2

### ISSUE THREAD

**Issue by simonpintarelli** [eth-cscs/spla#32]
```
     210    spla/src/gpu_util/gpu_runtime_api.hpp:258:13: note: in call to 'spla::gpu::StatusType spla::gpu::get_last_error()', declared h
            ere
     211      258 | inline auto get_last_error() -> StatusType { return GPU_PREFIX(GetLastError)(); }
     212          |             ^~~~~~~~~~~~~~
     213    spla/src/gpu_util/gpu_runtime_api.hpp:52:7: note: 'spla::gpu::StatusType' {aka 'hipError_t'} declared here
     214       52 | using StatusType = GPU_PREFIX(Error_t);
     215          |       ^~~~~~~~~~
  >> 216    spla/src/gpu_util/gpu_pointer_translation.hpp:60:26: error: 'using spla::gpu::PointerAttributes = hipPointerAttribute_t' {aka 
            'struct hipPointerAttribute_t'} has no member named 'memoryType'
     217       60 |   auto memoryType = attr.memoryType;
     218          |                          ^~~~~~~~~~
```

where `hipPointerAttribute_t` (from `/opt/rocm/include/hip/hip_runtime_api.h`) is:
```
/**
 * Pointer attributes
 */
typedef struct hipPointerAttribute_t {
    enum hipMemoryType type;
    int device;
    void* devicePointer;
    void* hostPointer;
    int isManaged;
    unsigned allocationFlags; /* flags specified when memory was allocated*/
    /* peers? */
} hipPointerAttribute_t;
``` 
Seems `memoryType` has been renamed to `type`?

**Comment by simonpintarelli** [comment]
Looks like this changed here: https://github.com/ROCm/HIP/commit/504e670d7329bf75a31f4b1ce0eae40346a59701

According to https://rocm.docs.amd.com/en/latest/about/changelog.html#hip-6-0-0 `memoryType` has been removed in major version 6, as already fixed in #33.
